### ISSUE TITLE
Add setting to specify spec suffix

### ISSUE THREAD

**Issue by Nautigsam** [lourenci/go-to-spec#4]
In my team we name our spec files like this: `file-spec.js` instead of `file.spec.js`. I think that would be great to define the suffix style in settings.

**Comment by lourenci** [comment]
Sorry for the late.
Could you open a pull request for this?

**Comment by lourenci** [comment]
Sorry for the late.
Can you open a pull request for this?

**Comment by Nautigsam** [comment]
I'm working on it, I will submit a PR once it's done.
